# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='aperture', max_length=500),
        ),
    ]
