# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170731_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
