# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170801_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionToken',
        ),
    ]
