# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20170802_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='updated_on',
        ),
    ]
