# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_commentmodel_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
