# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_upvote_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='created_on',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
