# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170802_2144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionToken',
        ),
    ]
